services:
    springboot:
        build:
          context: .
        ports:
           - 8085:8080
        environment:
           - MYSQL_USER:admin
           - MYSQL_PASSWORD:admin
        links:
           - db
        depends_on:
           - db
    db:
      image: mysql:8.0
      ports:
         - 3306:3306
      environment:
         - MYSQL_DATABASE:ecommjava
         - MYSQL_USER:admin
         - MYSQL_PASSWORD:admin
      volumes:
         - mysql:/var/lib/mysql
volumes:
    mysql:
