FROM maven:3.9.6-eclipse-temurin-11
COPY . .
RUN mvn clean install -DskipTests
CMD java -jar /root/.m2/repository/com/jtspringproject/JtSpringProject/0.0.1-SNAPSHOT/JtSpringProject-0.0.1-SNAPSHOT.jar

