services:
    springboot:
        build:
          context: .
        ports:
           - 8080:8080
        links:
           - db
        depends_on:
           - db
    db:
      image: mysql:8.0
      ports:
         - 3306:3306
      environment:
         - MYSQL_DATABASE:ecommjava
         - MYSQL_USER:root
         - MYSQL_PASSWORD:pass
         - MYSQL_ROOT_PASSWORD:root
      volumes:
         - mysql:/var/lib/mysql
volumes:
    mysql:

