services:
    springboot:
        build:
          context: .
        ports:
           - 8085:8080
        links:
           - db
        depends_on:
           - db
    db:
      image: mysql:8.0
      ports:
         - 33060:33060
      environment:
         - MYSQL_ROOT_PASSWORD:'pass'
         - MYSQL_DATABASE:'ecommjava'
         - MYSQL_USER:'root'
         - MYQL_PASSWORD:'pass' 
      volumes:
         - mysql:/var/lib/mysql
volumes:
    mysql:
